# domain: ej00668.github.io
# url: https://ej00668.github.io
# baseurl: /Mathematical_Modelling_of_Pre-clinical_Drug_Trials/
theme: jekyll-theme-cayman
title: Mathematical Modelling of Pre-clinical Drug Trials - Small molecule and Antibody Drug Conjugates
description: Esha Joshi
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
mathjax: true
