# domain: ej00668.github.io
# url: https://ej00668.github.io
# baseurl: /Mathematical_Modelling_of_Pre-clinical_Drug_Trials-/
theme: jekyll-theme-cayman
title: Understanding the Fine Movements of Badgers
description: Esha Joshi
